services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mathgame
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
